### ISSUE TITLE
app.js error causing it to not work..

### ISSUE THREAD

**Issue by kerneljay** [Scorpion-Development/D2D-Inventory#1]
![image](https://user-images.githubusercontent.com/116266395/235200331-5fc68590-35d3-4cdc-b919-f7bfc8af7103.png)

Steps to reproduce -- 

1. Close server down
2. Follow the step by step
3. Delete server cache
4. Load server up

The error occurs without operating the inventory and also when I restart the resource. It makes it impossible to use. Please fix

**Comment by kunaltak606** [comment]
fixed

**Comment by kerneljay** [comment]
Thanks dude
